#!/bin/sh
ulimit -c 0
total=0
pathsize=`/usr/bin/du -s --block-size=1 /home/sv1/K21_CLC/thai/decoder6_64/decoder6_64_icc2/work/signoff_check_drc_run/run_details --exclude=group | awk '{print $1}'`
total=$(($total+$pathsize))
group=0
group=`/usr/bin/du -s --block-size=1 /home/sv1/K21_CLC/thai/decoder6_64/decoder6_64_icc2/work/signoff_check_drc_run/run_details/group | awk '{print $1}'`
echo $group > /home/sv1/K21_CLC/thai/decoder6_64/decoder6_64_icc2/work/signoff_check_drc_run/run_details/group/duse_group.tmp && \
mv /home/sv1/K21_CLC/thai/decoder6_64/decoder6_64_icc2/work/signoff_check_drc_run/run_details/group/duse_group.tmp /home/sv1/K21_CLC/thai/decoder6_64/decoder6_64_icc2/work/signoff_check_drc_run/run_details/group/duse_group
pathsize=`/usr/bin/du -s --block-size=1 /home/sv1/K21_CLC/thai/decoder6_64/decoder6_64_icc2/work/signoff_check_drc_run/decoder6_64.LAYOUT_ERRORS | awk '{print $1}'`
total=$(($total+$pathsize))
echo $total > /home/sv1/K21_CLC/thai/decoder6_64/decoder6_64_icc2/work/signoff_check_drc_run/run_details/duse_manager_res.tmp && \
mv /home/sv1/K21_CLC/thai/decoder6_64/decoder6_64_icc2/work/signoff_check_drc_run/run_details/duse_manager_res.tmp /home/sv1/K21_CLC/thai/decoder6_64/decoder6_64_icc2/work/signoff_check_drc_run/run_details/duse_manager_res
